/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExcluirUsuario.java
 *
 * Created on 28/11/2010, 17:45:08
 */

package Visao.usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Controle.ControleUsuario;
import Controle.usuario.ExcluirUsuarioCtrl;

/**
 *
 * @author Cristiano
 */
public class ExcluirUsuario extends javax.swing.JFrame {
    private String id;

    /** Creates new form Excluir_Usuario */
    public ExcluirUsuario(String id_usuario) {
        initComponents();
        this.id = id_usuario;
    }

    private ExcluirUsuario() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSim = new javax.swing.JButton();
        jButtonnao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSim.setText("Sim");
        jButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimActionPerformed(evt);
            }
        });

        jButtonnao.setText("Não");
        jButtonnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel1.setText("Excluir Item?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSim)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonnao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSim)
                    .addComponent(jButtonnao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimActionPerformed
        ControleUsuario usuario = new ControleUsuario();
        usuario.setId_usuario(id);
        ExcluirUsuarioCtrl exclui = new ExcluirUsuarioCtrl(usuario);

        try {
            new GerenciarUsuarios().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ExcluirUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonSimActionPerformed

    private void jButtonnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnaoActionPerformed
        try 
       {
           new GerenciarUsuarios().setVisible(true);
       } catch (SQLException ex) {
           Logger.getLogger(InserirUsuario.class.getName()).log(Level.SEVERE, null, ex);
       }
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonnaoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSim;
    private javax.swing.JButton jButtonnao;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
